# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
    volumes:
     - C:\Users\OlhaShevel\OneDrive - SphereMall\Desktop\incode\projects\FRONTEND\issue-tracker\db:/var/lib/mysql 
  
